### ISSUE TITLE
Butttons are not clickable

### ISSUE THREAD

**Issue by rishavs** [Vladar4/ng2platformer#1]
I tried running the source@master. the game works fine but the title screen buttons are not clickable.
I have to use the quick start keys (enter,space) to get past the title screen.

here is the code for buttons;

```
# Play action procedure
proc play(widget: GuiWidget) =
    echo "Clicked Play"
    game.scene = mainScene
    
# Exit action procedure
proc exit(widget: GuiWidget) =
    gameRunning = false

proc init*(scene: TitleScene) =
    init Scene(scene)

    var
        btnPlay, btnExit: GuiButton
        btnPlayLabel, btnExitLabel: TextGraphic

    # Play button
    btnPlayLabel = newTextGraphic(defaultFont)
    btnPlayLabel.setText("PLAY")
    btnPlay = newGuiButton(buttonSkin, btnPlayLabel)
    btnPlay.centrify()
    btnPlay.pos = (GameWidth / 2, GameHeight / 2)
    btnPlay.actions.add(play) # assign the action procedure
    scene.add(btnPlay)

    # Exit button
    btnExitLabel = newTextGraphic(defaultFont)
    btnExitLabel.setText("EXIT")
    btnExit = newGuiButton(buttonSkin, btnExitLabel)
    btnExit.centrify()
    btnExit.pos = (GameWidth / 2, GameHeight / 2 + 64)
    btnExit.actions.add(exit) # assign the action procedure
    scene.add(btnExit)
```

**Comment by Vladar4** [comment]
Might be the similar issue: https://github.com/Vladar4/nimgame2/issues/33

Please, check the [compilation flags](https://github.com/Vladar4/nimgame2#recommended-compilation-flags)

**Comment by rishavs** [comment]
I tried with the compilation flags `--multimethods:on -d:release --opt:speed` but that didnt help. I am using 0.6.1.

Edit: I tried the compilation flags with both the ng2platformer source and my own custom project.

**Comment by Vladar4** [comment]
That's strange: I just compiled the ng2platformer master source with 0.6.1 and buttons work as intended.
Do you use Nim v1.x.x ?

**Comment by rishavs** [comment]
Nim Compiler Version 0.20.0 [Windows: amd64]
nimgame2  [#devel, 0.6.1]

**Comment by Vladar4** [comment]
Just tried it with 0.20.0 on Linux and, just in case, under wine — still works fine if I pass `--multimethods:on`

Just to check, do the buttons highlight when you hover on them or they are completely frozen?

**Comment by rishavs** [comment]
I just took another download of the master and now that works fine.

But my custom project still has the issue. the buttons are just frozen and have no hover effect. My code is here;
https://github.com/rishavs/ng2snek

**Comment by Vladar4** [comment]
Well, you have parent event call commented out right now
https://github.com/rishavs/ng2snek/blob/d052fd73a9856d32107d8eec10c0ae701761f5ef/src/scenes/title.nim#L89

**Comment by rishavs** [comment]
yikes. Thanks for catching that. It is working fine now.
